CREATE TABLE IF NOT EXISTS JOB
(
    ID CHAR(4),
    CONTENT VARCHAR2 (100),
    REG_DATE TIMESTAMP,
    UPD_DATE TIMESTAMP,
    COMPLETE_YN CHAR(1),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS JOB_REF
(
    ID CHAR(4),
    REF_ID CHAR(4),
    REG_DATE TIMESTAMP,
    PRIMARY KEY (ID, REF_ID)
);

CREATE SEQUENCE IF NOT EXISTS JOB_SEQ START WITH 1 INCREMENT BY 1;
